Haar feature 기반 cascade classifier(다단계분류)를 이용한 객채검출에 대해서 얼굴 검출을 위한 코드를 작성하려고 한다.

Haar cascade classifier는 2001년 Paul Viola와 Micheal Jones의 논문인 'Rapid Object Detection using a Boossed Cascde of simple Feature'에서 제안된 효과적인 검출 방법이다.

이방법은 다수의 객채이미지(positive)와 객체가 아닌 이미지(negative)를 cascade함수로 트레이닝 시켜 객체 검출을 달성하는 머신러닝 기반의 접근방법이다.

먼저, 얼굴검출을 위해 많은 수의 얼굴 이미지와 얼굴이 없는 이미지를 classifier에 트레이닝 시켜 얼굴에 대한 특징들을 추출해서 데이터로 저장해 두어야 한다.

In [2]:
import numpy as np
import cv2

font = cv2.FONT_HERSHEY_SIMPLEX
def faceDetect():
    eye_detect = False
    face_cascade = cv2.CascadeClassifier('datasets/haarcascade_frontface.xml')
    eye_cascade = cv2.CascadeClassifier('datasets/haarcascade_eye.xml')
    info = ''
    
    try:
        cap = cv2.VideoCapture(0)# 비디오 킨다.
    except:
        print('카메라 로딩 실패')
        return
    
    while True:
        ret, frame = cap.read() #비디오 데이터 불러오기
        if not ret:
            break
        
        if eye_detect:
            info = 'Eye Detection On'
        else:
            info = 'Eye Detection Off'
            
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.3, 5)
        
        cv2.putText(frame, info, (5, 15), font, 0.5, (255,0,255), 1)
        
        for (x,y,w,h) in faces:    
            cv2.rectangle(frame, (x,y),(x+w,y+h),(255, 0, 0), 2)
            cv2.putText(frame, 'Detected Face',(x-5,y-5), font, 0.5, (255,255,0), 2)
            if eye_detect:
                roi_gray = gray[y:y+h, x:x+w]
                roi_color = frame[y:y+h, x:x+w]
                eyes = eye_cascade.detectMultiScale(roi_gray)
                for (ex, ey, ew, eh) in eyes:
                    cv.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh),(0, 255, 0), 2)
                    
        cv2.imshow('frame',frame)
        k = cv2.waitKey(30)
        if k == ord('i'):
            eye_edtect = not eye_detect
        if k == 27:
            break
                
    cap.release()
    cv2.destroyAllWindows()

faceDetect()

 - face_cascade = cv2.CascadeClassifier('datasets/haarcascade_frontface.xml')
 - eye_cascade = cv2.CascadeClassifier('datasets/haarcascade_eye.xml')
 
 얼굴 검출과 눈 검출을 위한 Haar-Cascade 트레이닝 데이터를 각각 읽어 CascadeClassifier 객채를 생성합니다. 
 

- faces = face_cascade.detectMultiScale(gray, 1.3, 5)

detectMultiScale함수에 grayscale 이미지를 입력하여 얼굴을 검출합니다. 얼굴이 검출되면 위치를 리스트로 리턴합니다. 위치는 (x,y,w,h)와 같은 튜플이며 (x,y)는 검출된 얼굴의 좌상단 위치, w,h는 가로,세로크기 입니다.

detectMultiScale()의 성분 1.3은 ScaleFactor, 5는 minNeighbor를 의미하는 값

- roi_gray = gray[y:y+h, x:x+w]
- roi_color = frame[y:y+h, x:x+w]
- eyes = eye_cascade.detectMultiScale(roi_gray)

사람눈을 검출하기 위해서 검출된 얼굴 영역에서 눈을 검출하는 것이다. 검출되면 그 위치를 리스트로 리턴합니다.

## 이미지에서 얼굴 검출하기

In [2]:
import numpy as np
import cv2

font = cv2.FONT_HERSHEY_SIMPLEX
def faceDetect():
    eye_detect = True
    face_cascade = cv2.CascadeClassifier('datasets/haarcascade_frontface.xml')
    eye_cascade = cv2.CascadeClassifier('datasets/haarcascade_eye.xml')
    info = ''
    
    try:
        imgfile = 'image/people3.jpg' #이미지 저장 디렉토리
        frame = cv2.imread(imgfile, cv2.IMREAD_COLOR) # 이미지 불러오기
    except:
        print('이미지 로딩 실패')
        return
            
    if eye_detect:
        info = 'Eye Detection On'
    else:
        info = 'Eye Detection Off'
            
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
        
    cv2.putText(frame, info, (5, 15), font, 0.5, (255,0,255), 1)
        
    for (x,y,w,h) in faces:    
        cv2.rectangle(frame, (x,y),(x+w,y+h),(255, 0, 0), 2)
        cv2.putText(frame, 'Detected Face',(x-5,y-5), font, 0.5, (255,255,0), 2)
        if eye_detect:
            roi_gray = gray[y:y+h, x:x+w]
            roi_color = frame[y:y+h, x:x+w]
            eyes = eye_cascade.detectMultiScale(roi_gray)
            for (ex, ey, ew, eh) in eyes:
                cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh),(0, 255, 0), 2)
    
    
    cv2.namedWindow('frame',cv2.WINDOW_NORMAL)
    cv2.imshow('frame', frame)
    cv2.waitKey(0)
    
    k = cv2.waitKey(0) & 0xFF
    if k ==27:     
        cv2.destroyAllWindows()  
    elif k == ord('c'):
        cv2.imwrite('image/people3_copy.jpg',gray)
        cv2.destroyAllWindows()

faceDetect()

 #### 흑백사진으로 저장하기 

In [6]:
import numpy as np
import cv2

font = cv2.FONT_HERSHEY_SIMPLEX
def faceDetect():
    eye_detect = True
    face_cascade = cv2.CascadeClassifier('datasets/haarcascade_frontface.xml')
    eye_cascade = cv2.CascadeClassifier('datasets/haarcascade_eye.xml')
    info = ''
    
    try:
        imgfile = 'image/people3.jpg' #이미지 저장 디렉토리
        frame = cv2.imread(imgfile, cv2.IMREAD_COLOR) # 이미지 불러오기
    except:
        print('이미지 로딩 실패')
        return
            
    if eye_detect:
        info = 'Eye Detection On'
    else:
        info = 'Eye Detection Off'
            
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
        
    cv2.putText(frame, info, (5, 15), font, 0.5, (255,0,255), 1)
        
    for (x,y,w,h) in faces:    
        cv2.rectangle(gray, (x,y),(x+w,y+h),(255, 0, 0), 2)
        cv2.putText(gray, 'Detected Face',(x-5,y-5), font, 0.5, (255,255,0), 2)
        if eye_detect:
            roi_gray = gray[y:y+h, x:x+w]
            roi_color = frame[y:y+h, x:x+w]
            eyes = eye_cascade.detectMultiScale(roi_gray)
            for (ex, ey, ew, eh) in eyes:
                cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh),(0, 255, 0), 2)
    
    print('얼굴 좌표:',faces)
    cv2.namedWindow('gray',cv2.WINDOW_NORMAL)
    cv2.imshow('gray', gray)
    cv2.waitKey(0)
    
    k = cv2.waitKey(0) & 0xFF
    if k ==27:     
        cv2.destroyAllWindows()  
    elif k == ord('c'):
        cv2.imwrite('image/people3_copy_g.jpg',gray)
        cv2.destroyAllWindows()

faceDetect()

얼굴 좌표: [[ 710  232   39   39]
 [ 358  248   42   42]
 [1020  257   42   42]
 [ 524  499   48   48]
 [ 737  514   45   45]
 [ 865  524   44   44]
 [ 984  536   47   47]
 [ 878  304   47   47]
 [ 753  317   40   40]
 [ 387  316   44   44]
 [1008  598   50   50]
 [ 319  179   46   46]
 [ 521  196   47   47]
 [ 975  204   43   43]
 [ 227  219   46   46]
 [ 604  220   47   47]
 [ 106  230   48   48]
 [ 910  227   48   48]
 [1123  234   49   49]
 [ 255  487   51   51]
 [ 137  501   52   52]
 [1276  266   50   50]
 [ 637  511   48   48]
 [ 378  514   49   49]
 [1127  525   54   54]
 [1090  311   52   52]
 [ 491  317   50   50]
 [ 979  321   49   49]
 [1287  557   52   52]
 [ 170  329   53   53]
 [ 503  569   52   52]
 [ 882  571   54   54]
 [ 628  576   51   51]
 [ 754  577   49   49]
 [ 163  183   47   47]
 [ 282  344   49   49]
 [ 231  581   49   49]
 [ 421  190   49   49]
 [ 642  190   47   47]
 [ 365  582   56   56]
 [1075  207   47   47]
 [1176  208   45   45]
 [1094  615   53   53]
 [12